#!/bin/bash

# Program to run a program with recording of the code and results for
# reproducibility.

git add -u
git commit -m again_$(date --iso-8601=seconds)

COMMIT=$(git rev-parse --short HEAD)
PREV_COMMIT=$(git rev-parse --short HEAD^1)

rm -rf inputs output
mkdir -p output tries/$COMMIT

tar xzf inputs.tgz

make run > output/stdout 2> output/stderr
cat output/stdout output/stderr

mv output tries/$COMMIT/

if [ -d tries/$PREV_COMMIT/output ]
then
    diff -r tries/$COMMIT/output tries/$PREV_COMMIT/output > tries/$COMMIT/output.diff
fi
git diff $PREV_COMMIT $COMMIT > tries/$COMMIT/code.diff
