#!/bin/bash

# Script to remove "again" commits from a certain way back

EDITOR='gsed --in-place -e "/${1-1}/,\$s/pick \\([0-9a-f]*\\) again-/fixup \\1 again-/"' git rebase -i $(git rev-list --max-parents=0 HEAD)
